name: codecov

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codecov:
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
